### PR TITLE
Var cleanup

### PR DESCRIPTION
**Pull request by srevenant**
This follows after the jump fix.  It switches from `var` to `let` and `const` which is easier to debug

### CODE REVIEW

**Comment by wpnetninjas** [comment]
Great fix @srevenant  - @tgomilar when will this be merged?

**Comment by manikbajaj** [comment]
@srevenant Unfortunately this breaks the background parallax option. Needs to be tested before merging! @tgomilar lots of people are facing this issue, a solution is needed. I am facing the same problem.

**Comment by wpnetninjas** [comment]
Hmm we are using background parallax with this fix and is working well.

________________________________

**Comment by manikbajaj** [comment]
@wpnetninjas I am using this as a RequireJs module. Try loading it as a RequireJs module it doesn't work and it's just the background parallax that doesn't work. @srevenant let me know if you want me to post the RequieJs config over here and I'll do it!

**Comment by srevenant** [comment]
Go for it.

**Comment by tgomilar** [comment]
@srevenant Thank you, great fix!

**Pull request merged**
